name: Ruby Workflow
on:
 # push:
 #   branches: [ main ]
 # pull_request:
 #   branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Install dependencies
      run: bundle install

    # - name: Build Applications
    #   run: |
    #     ruby lib/main.rb
        

    - name: Run tests
      run: | 
          bundle exec rspec

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ruby


    - name: Autobuild CodeQL database
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        languages: ruby
